import { CatsInterface } from "./interfaces"

export const SearchingCats: CatsInterface[] = [
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Мотя и Яна",
    age: "2-3 года",
    trueAge: 3,
    gender: "MF",
    sterelized: true,
    bio: "Тихая и спокойная парочка. Брать только вместе.",
    basics: "Привиты и стерилизованы / Приучены к лотку",
    img: "мотя_яна",
    vk: "https://vk.com/prosto__koshki?z=photo-212806052_457240440%2Falbum-212806052_283766290",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Марся",
    age: "7 месяцев",
    trueAge: 0.7,
    gender: "F",
    sterelized: true,
    bio: "Ласковая кошечка, немного робкая.",
    basics: "Привита и обработана / Приучена к лотку",
    img: "марся",
    vk: "https://vk.com/prosto__koshki?z=photo-212806052_457240840%2Falbum-212806052_283766290",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Маняша",
    age: "2 года",
    trueAge: 2,
    gender: "F",
    sterelized: true,
    bio: "Ласковая, спокойная кошечка.",
    basics: "Привита и обработана / Приучена к лотку / Стерилизована",
    img: "маняша",
    vk: "https://vk.com/prosto__koshki?z=photo-212806052_457240224%2Falbum-212806052_283766290",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Ватсон",
    age: "5 лет",
    trueAge: 5,
    gender: "M",
    sterelized: true,
    bio: "Ласковый и общительный кот!",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "ватсон",
    vk: "https://vk.com/album-212806052_295647785",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Ники",
    age: "2 года",
    trueAge: 2,
    gender: "F",
    sterelized: true,
    bio: "Ласковая, спокойная и скромная кошечка.",
    basics: "Привита и обработана / Приучена к лотку / Стерилизована",
    img: "ники",
    vk: "https://vk.com/photo-212806052_457245958",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Фая",
    age: "4 месяца",
    trueAge: 0.4,
    gender: "F",
    sterelized: false,
    bio: "Ласковая, спокойная и скромная кошечка.",
    basics: "Привита и обработана / Приучена к лотку",
    img: "фая",
    vk: "https://vk.com/photo-212806052_457245509",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Наташа",
    age: "2 года",
    trueAge: 2,
    gender: "F",
    sterelized: true,
    bio: "Ласковая и спокойная.",
    basics: "Привита и обработана / Приучена к лотку / Стерилизована",
    img: "наташа",
    vk: "https://vk.com/photo-212806052_457245845",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Рики",
    age: "2 года",
    trueAge: 2,
    gender: "F",
    sterelized: true,
    bio: "Ласковая и скромная.",
    basics: "Привита и обработана / Приучена к лотку / Стерилизована",
    img: "рики",
    vk: "https://vk.com/photo-212806052_457245963",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Лапкин-Шляпкин",
    age: "5 лет",
    trueAge: 5,
    gender: "M",
    sterelized: true,
    bio: "Спокойный котик.",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "лапкин-шляпкин",
    vk: "https://vk.com/photo-212806052_457245947",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Лелик",
    age: "2-3 года",
    trueAge: 2,
    gender: "M",
    sterelized: true,
    bio: "Спокойный и ласковый котик.",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "лелик",
    vk: "https://vk.com/photo-212806052_457245189",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Булочка",
    age: "2 года",
    trueAge: 2,
    gender: "F",
    sterelized: true,
    bio: "Спокойная и ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку / Стерелизована",
    img: "булочка",
    vk: "https://vk.com/photo-212806052_457245794",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Люси",
    age: "1 год",
    trueAge: 1,
    gender: "F",
    sterelized: true,
    bio: "Спокойная и очень ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку / Стерелизована",
    img: "люси",
    vk: "https://vk.com/photo-212806052_457245487",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Ушаня",
    age: "1 год",
    trueAge: 1,
    gender: "F",
    sterelized: true,
    bio: "Спокойная и ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку / Стерелизована",
    img: "ушаня",
    vk: "https://vk.com/photo-212806052_457246051",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Фил",
    age: "3 месяца",
    trueAge: 0.3,
    gender: "M",
    sterelized: false,
    bio: "Игривый и ласковый котик.",
    basics: "Обработан / Привит / Приучен к лотку / Игривый",
    img: "фил",
    vk: "https://vk.com/photo-212806052_457245270",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Бусинка",
    age: "4 месяца",
    trueAge: 0.4,
    gender: "F",
    sterelized: false,
    bio: "Игривая и ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку / Ласковая",
    img: "бусинка",
    vk: "https://vk.com/photo-212806052_457245777",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Пол",
    age: "4 месяца",
    trueAge: 0.4,
    gender: "M",
    sterelized: false,
    bio: "Игривый и ласковый котик.",
    basics: "Обработан / Привит / Приучен к лотку / Игривый",
    img: "пол",
    vk: "https://vk.com/photo-212806052_457245756",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Альф",
    age: "1-2 года",
    trueAge: 1,
    gender: "M",
    sterelized: true,
    bio: "Игривый и ласковый котик.",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "альф",
    vk: "https://vk.com/photo-212806052_457245435",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Нюша",
    age: "1-2 года",
    trueAge: 1,
    gender: "F",
    sterelized: false,
    bio: "Игривая и очень ласковая кошечка. У Нюши мозжечковая атаксия, это нарушение координации и произвольных движений.",
    basics: "Обработана / Привита / Приучена к лотку / Ласковая / Стерелизована / 'Особенная' кошечка",
    img: "нюша",
    vk: "https://vk.com/album-212806052_294914672",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Фиона",
    age: "3 месяца",
    trueAge: 0.3,
    gender: "F",
    sterelized: false,
    bio: "Игривая и ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку",
    img: "фиона",
    vk: "https://vk.com/photo-212806052_457245255",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Ромашкин",
    age: "1-2 года",
    trueAge: 1,
    gender: "M",
    sterelized: true,
    bio: "Ласковый котик.",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "ромашкин",
    vk: "https://vk.com/photo-212806052_457245177",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Фиби",
    age: "3 месяца",
    trueAge: 0.3,
    gender: "F",
    sterelized: false,
    bio: "Игривая и ласковая кошечка.",
    basics: "Обработана / Привита / Приучена к лотку",
    img: "фиби",
    vk: "https://vk.com/photo-212806052_457245294",
  },
  {
    category: "S",
    id: crypto.randomUUID(),
    name: "Носик",
    age: "2-3 года",
    trueAge: 2,
    gender: "M",
    sterelized: true,
    bio: "Ласковый и спокойный котик.",
    basics: "Обработан / Привит / Приучен к лотку / Кастрирован",
    img: "носик",
    vk: "https://vk.com/photo-212806052_457245158",
  },
]

export const HomeCats: CatsInterface[] = [
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Тоша",
    gender: "M",
    bio: "Тошу забрали домой Юля и Илья в сентябре 2021. С тех пор он живёт счастливой домашней жизнью.",
    img: "тоша",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Сабрина",
    gender: "F",
    bio: "Во время жизни в приюте Сабрина дружила с Тошей. Однако, их пути разошлись в сентябре 2021 года, когда Тошу забрали домой Юля и Илья. Но в этом мире не без чудес! В январе 2022 года Тоша и Сабрина воссоединились - её забрали домой к её другу Тоше!",
    img: "сабрина",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Мишка",
    gender: "M",
    bio: "Мишка уехал домой 29.04.2022!",
    img: "мишка",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Ариша",
    gender: "F",
    bio: "Ариша уехала домой 11.05.2022!",
    img: "ариша",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Пуговка",
    gender: "F",
    bio: "Пуговка уехала домой 15.05.2022!",
    img: "пуговка",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Забава",
    gender: "F",
    bio: "Забава уехала домой 22.05.2022!",
    img: "забава",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Каштан",
    gender: "M",
    bio: "Каштан уехал домой 22.05.2022!",
    img: "каштан",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Милли",
    gender: "F",
    bio: "Милли уехала домой 23.05.2022!",
    img: "милли",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Флорис",
    gender: "F",
    bio: "Флорис уехала домой 29.05.2022!",
    img: "флорис",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Амурка",
    gender: "F",
    bio: "Амурка уехала домой 04.06.2022!",
    img: "амурка",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Йоши",
    gender: "M",
    bio: "Йоши уехал домой летом 2022!",
    img: "йоши",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Чипс",
    gender: "M",
    bio: "Чипс уехал домой летом 2022!",
    img: "чипс",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Мушкетер",
    gender: "M",
    bio: "Мушкетер уехал домой летом 2022!",
    img: "мушкетер",
  },
  {
    category: "H",
    id: crypto.randomUUID(),
    name: "Кузя",
    gender: "M",
    bio: "Кузя уехал домой летом 2022!",
    img: "кузя",
  },
]
